### ISSUE TITLE
Help! Export Mesh from Depth

### ISSUE THREAD

**Issue by lif314** [limacv/GaussianSplattingViewer#12]
![color_3](https://github.com/limacv/GaussianSplattingViewer/assets/63114150/a31e8c4b-9043-498f-90b0-cb04323f0c0a)
I've found that my model's depth map is quite good, and I want to export it as a mesh. However, I'm not familiar with GLSL at all. Is it possible to do this?

**Comment by lif314** [comment]
I have implemented Mesh extraction based on [DreamGaussian](https://github.com/dreamgaussian/dreamgaussian), but the effect is not good. Is there any other possible integration solution?
![image](https://github.com/limacv/GaussianSplattingViewer/assets/63114150/533357ad-d3ea-4f18-ade5-f67ce36418ca)
![image](https://github.com/limacv/GaussianSplattingViewer/assets/63114150/fc04c1b2-80a9-484d-9327-793542461065)

**Comment by limacv** [comment]
Although this is not a task for a viewer, I suggest you could render the depth map using the official CUDA rasterize (replacing RGB with depth value), and then use some 3D processing library to convert depth map to a 3D point cloud or 3D mesh (e.g. open3d). Please don't use the depth map directly saved from viewer because that will only give you 8-bit precision depth map, and result in poor geometry

**Comment by lif314** [comment]
> Although this is not a task for a viewer, I suggest you could render the depth map using the official CUDA rasterize (replacing RGB with depth value), and then use some 3D processing library to convert depth map to a 3D point cloud or 3D mesh (e.g. open3d). Please don't use the depth map directly saved from viewer because that will only give you 8-bit precision depth map, and result in poor geometry

Thank you for your suggestion, I will give it a try! And I will close this issue.
